### ISSUE TITLE
metadata scheme

### ISSUE THREAD

**Issue by rjoberon** [fcatools/contexts#7]
We need to agree upon a metadata scheme, i.e., what to include and how to describe it. Currently, we use a simple YAML schema which looks as follows:

```yaml
animals_en.cxt:
  title: Animals
  source: "Ganter, B., Wille, R., & Stumme, G. (2005). Formal Concept Analysis: Foundations and Applications (Vol. 3626). Springer, p. 27"
  size:
    objects: 35
    attributes: 11
  language: English
  description: animals and their characteristics
```

**Comment by perasperaadastra** [comment]
Currently, it looks like this:
```
# metadata.schema.yaml
type: object
required:
  - title
  - source
  - size
  - language
  - description
properties:
  title:
    type: string
  source:
    type: string
  size:
    type: object
    required:
      - objects
      - attributes
    properties:
      objects:
        type: integer
        minimum: 1
      attributes:
        type: integer
        minimum: 1
  language:
    type: string
  description:
    type: string
```
Together with the points raised in #6 it might be helpful to change the type of "language" to something like
```
language:
  anyOf:
    - type: string
      pattern: "^[a-z]{2}$"   # restriction to only ISO 639-1 two-letter code
    - type: array
      items:
        type: string
        pattern: "^[a-z]{2}$" # each item must also be a valid code
      minItems: 1
      uniqueItems: true
```
or replace it with
```
oneOf:
  - type: object
    required: [language]
    properties:
      language:
        type: string
        pattern: "^[a-z]{2}$"   # restriction to only ISO 639-1 two-letter code
    additionalProperties: false
  - type: object
    required: [languages]
    properties:
      languages:
        type: array
        items:
          type: string
          pattern: "^[a-z]{2}$" # each item must also be a valid code
        minItems: 2
        uniqueItems: true
    additionalProperties: false
```
